version: '3.7'

services:
  traefik:
    image: traefik:1.7.16-alpine
    command: --web --docker
    ports:
      #      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ${PROJECTS:-./}/traefik.toml:/traefik.toml
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=front"
      - "traefik.port=8080"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.wako057.net"
    networks:
      front:


networks:
  front:
    name: front
    ipam:
      config:
        - subnet: 192.168.42.0/24
  back:
    name: back
    ipam:
      config:
        - subnet: 192.168.54.0/24
